In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fatemehmohammadinia/heart-attack-dataset-tarik-a-rashid")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/fatemehmohammadinia/heart-attack-dataset-tarik-a-rashid/1.archive...

100%|██████████| 15.9k/15.9k [00:00<00:00, 14.3MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/fatemehmohammadinia/heart-attack-dataset-tarik-a-rashid/versions/1

In [ ]:
ls /kaggle/input/heart-attack-dataset-tarik-a-rashid/Medicaldataset.csv

ls: cannot access '/kaggle/input/heart-attack-dataset-tarik-a-rashid/Medicaldataset.csv': No such file or directory

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('/root/.cache/kagglehub/datasets/fatemehmohammadinia/heart-attack-dataset-tarik-a-rashid/versions/1/Medicaldataset.csv')

In [ ]:
data.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
0,64,1,66,160,83,160.0,1.80,0.012,negative
1,21,1,94,98,46,296.0,6.75,1.060,positive
2,55,1,64,160,77,270.0,1.99,0.003,negative
3,64,1,70,120,55,270.0,13.87,0.122,positive
4,55,1,64,112,65,300.0,1.08,0.003,negative

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1319 non-null   int64
 1   Gender                    1319 non-null   int64
 2   Heart rate                1319 non-null   int64
 3   Systolic blood pressure   1319 non-null   int64
 4   Diastolic blood pressure  1319 non-null   int64
 5   Blood sugar               1319 non-null   float64
 6   CK-MB                     1319 non-null   float64
 7   Troponin                  1319 non-null   float64
 8   Result                    1319 non-null   object
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1319 non-null   int64
 1   Gender                    1319 non-null   int64
 2   Heart rate                1319 non-null   int64
 3   Systolic blood pressure   1319 non-null   int64
 4   Diastolic blood pressure  1319 non-null   int64
 5   Blood sugar               1319 non-null   float64
 6   CK-MB                     1319 non-null   float64
 7   Troponin                  1319 non-null   float64
 8   Result                    1319 non-null   object
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB

In [ ]:
data.Result.value_counts()

Result
positive    810
negative    509
Name: count, dtype: int64

In [ ]:
X = data.drop('Result', axis=1)
y = data['Result']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)
print(f"Original classes: {le.classes_}")
print(f"Encoded values: {le.transform(le.classes_)}")
print(f"First 5 encoded target values: {y_encoded[:5]}")

Original classes: ['negative' 'positive']
Encoded values: [0 1]
First 5 encoded target values: [0 1 0 1 0]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (1055, 8)
X_test shape: (264, 8)
y_train shape: (1055,)
y_test shape: (264,)

In [ ]:
print("Unique values in Gender column:", X_train['Gender'].unique())

# Based on the unique values, 'Gender' (0 and 1) is a categorical feature. All other features are numerical.
categorical_features = ['Gender']
numerical_features = X_train.columns.drop(categorical_features).tolist()

Unique values in Gender column: [1 0]

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ])

# Apply the preprocessing to the training and testing sets
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print(f"X_train_processed shape: {X_train_processed.shape}")
print(f"X_test_processed shape: {X_test_processed.shape}")

X_train_processed shape: (1055, 9)
X_test_processed shape: (264, 9)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Initialize and train the Logistic Regression model
model = LogisticRegression(random_state=42)
model.fit(X_train_processed, y_train)

# Make predictions on the preprocessed test set
y_pred = model.predict(X_test_processed)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

Model Accuracy: 0.7992

In [ ]:
import joblib

In [ ]:
joblib.dump(model,'unniappam.pkl')

['unniappam.pkl']